""" 'About' dialog window generated by QtDesigner"""
from PyQt5 import QtCore, QtGui, QtWidgets


class UiAboutDialog(object):
    """Creates an 'About' dialog window"""

    def setupUi(self, Dialog):
        """Sets up 'About' dialog window"""

        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 350)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignCenter | QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse
        )
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/icons8-om-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton.clicked.connect(Dialog.accept)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        """Adds formatted text to the 'About' dialog window"""

        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        self.label.setText(
            _translate(
                "Dialog",
                "<b>SansConverter</b>"
                "<br/>"
                "<br/>"
                "SansConverter is an offline tool to easily convert romanized Sanskrit text from one system of "
                "transliteration to another."
                "<br/>"
                "<br/>"
                "It can also be used to type in Sanskrit text with diacritics (using HK or Velthuis systems)."
                "<br/>"
                "<br/>"
                "Copyright © 2022 Kostiantyn Perun."
                "<br/>"
                "Version 1.7"
                "<br/>"
                '<a href="https://github.com/Perun108">https://github.com/Perun108</a>'
                "<br/>"
                "<br/>"
                'Send your feedback or suggestions to <a href= "mailto: kosperun@gmail.com">kosperun@gmail.com</a>',
            )
        )
        self.pushButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UiAboutDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
